export class RoutePaths {
  static readonly LOGIN: string = 'features/auth/pages/LoginPage';
  static readonly REGISTER: string = 'features/auth/pages/RegisterPage';
  static readonly NAVIGATION: string = 'features/home/pages/NavigationPage';
  static readonly HOME: string = 'features/home/pages/HomePage';
  static readonly BARTENDING_STATION: string = 'features/home/pages/BartendingStationPage';
  static readonly RECIPE_LIBRARY: string = 'features/recipe/pages/RecipeLibraryPage';
  static readonly RECIPE_DETAIL: string = 'features/recipe/pages/RecipeDetailPage';
  static readonly AI_COCKTAIL: string = 'features/cocktail/pages/AICocktailPage';
  static readonly FAVORITE: string = 'features/favorite/pages/MyFavoritePage';
  static readonly MATERIAL_SCANNER: string = 'features/station/pages/MaterialScannerPage';
  static readonly MATERIAL_LIBRARY: string = 'features/station/pages/MaterialLibraryPage';
  static readonly COMMUNITY: string = 'features/community/pages/CommunityPage';
  static readonly COMMUNITY_DETAIL: string = 'features/community/pages/CommunityPostDetailPage';
  static readonly COMMUNITY_EDITOR: string = 'features/community/pages/CommunityNoteEditorPage';
  static readonly PROFILE: string = 'features/profile/pages/ProfilePage';
  static readonly PROFILE_POSTS: string = 'features/profile/pages/ProfilePostsPage';
  static readonly PROFILE_SETTINGS: string = 'features/profile/pages/ProfileSettingsPage';
}
